[versions]
apksig = "8.13.2"
apktoolLib = "2.12.1"
bcprovJdk18on = "1.83"
commonsIo = "2.21.0"
guava = "33.5.0-android"
prov = "1.58.0.0"
snakeyaml = "2.5"
zipsigner = "1.6"
log4j = "1.2.17"
desugar_jdk_libs = "2.1.5"

[libraries]
androidx-core-ktx-v1160 = "androidx.core:core-ktx:1.17.0"
androidx-appcompat = "androidx.appcompat:appcompat:1.7.1"
apksig = { module = "com.android.tools.build:apksig", version.ref = "apksig" }
apktool-lib = { module = "org.apktool:apktool-lib", version.ref = "apktoolLib" }
bcpkix-jdk15on = { module = "com.madgag.spongycastle:bcpkix-jdk15on", version.ref = "prov" }
bcprov-jdk18on = { module = "org.bouncycastle:bcprov-jdk18on", version.ref = "bcprovJdk18on" }
commons-io-v2200 = { module = "commons-io:commons-io", version.ref = "commonsIo" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
material = "com.google.android.material:material:1.13.0"
androidx-activity-ktx = "androidx.activity:activity-ktx:1.12.2"
commons-lang3 = "org.apache.commons:commons-lang3:3.20.0"
commons-io = "commons-io:commons-io:2.21.0"
androidx-media3-exoplayer = "androidx.media3:media3-exoplayer:1.9.0"
apktool-lib-v261 = { group = "io.github.ibotpeaches", name = "apktool-lib", version = "2.6.1" }
prov = { module = "com.madgag.spongycastle:prov", version.ref = "prov" }
snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }
xercesimpl = { group = "xerces", name = "xercesImpl", version = "2.12.2" }
zipsigner = { module = "com.github.kellinwood:zipsigner", version.ref = "zipsigner" }
log4j = { module = "log4j:log4j", version.ref = "log4j" }
desugar-jdk-libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }

[plugins]
