[versions]
apktoolLib = "2.12.1"
commonsIo = "2.20.0"
guava = "33.5.0-android"
snakeyaml = "2.5"

[libraries]
androidx-core-ktx-v1160 = "androidx.core:core-ktx:1.16.0-alpha01"
androidx-appcompat = "androidx.appcompat:appcompat:1.7.0"
apktool-lib = { module = "org.apktool:apktool-lib", version.ref = "apktoolLib" }
commons-io-v2200 = { module = "commons-io:commons-io", version.ref = "commonsIo" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
material = "com.google.android.material:material:1.13.0"
androidx-activity-ktx = "androidx.activity:activity-ktx:1.9.1"
commons-lang3 = "org.apache.commons:commons-lang3:3.17.0"
commons-io = "commons-io:commons-io:2.16.1"
androidx-media3-exoplayer = "androidx.media3:media3-exoplayer:1.4.0"
apktool-lib-v261 = { group = "io.github.ibotpeaches", name = "apktool-lib", version = "2.6.1" }
snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }
xercesimpl = { group = "xerces", name = "xercesImpl", version = "2.12.2" }

[plugins]
